#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 19 09:29:11 2025

@author: benjamin
"""

import os
import Sofa
import SofaRuntime
import numpy as np
from scipy.spatial.transform import Rotation as R 
#from stlib.physics.deformable import ElasticMaterialObject
#from stlib.physics.constraints import FixedBox
#from stlib.physics.collision import CollisionMesh
from stlib3.scene import Scene
from splib3.animation import animate
import Geometries.Constants as Const
import rigidification


dirPath = os.path.dirname(os.path.abspath(__file__)) + '/'
path = os.path.dirname(os.path.abspath(__file__))+'/Meshes/'
MeshesPath = os.path.dirname(os.path.abspath(__file__))+'/Geometries/'
GeneratedMeshesPath = os.path.dirname(os.path.abspath(__file__))+'/Geometries/'
TempPath = os.path.dirname(os.path.abspath(__file__))+'/Temp/'

# offsetX = 10.0
# offsetZ = 4

# SmallBox = [
#     3 + offsetX, 0.5, 0.5 + offsetZ,   # x_max, y_max, z_max
#    -0.5 + offsetX,-0.5,-0.5 + offsetZ    # x_min, y_min, z_min
# ]

def normal_trajectory(points):

    pts = np.array(points)
    x_vals = np.unique(pts[:, 0])

    trayectoria = []
    invertir = False

    for x in x_vals:
        columna = pts[pts[:, 0] == x]
        columna = columna[np.argsort(columna[:, 1])]
        if invertir:
            columna = columna[::-1]

        for p in columna:
            x_, y_ = p
            trayectoria.append([x_, y_, Const.MagneticSkinHeight])  

        invertir = not invertir

    return np.array(trayectoria)


def calculate_B_field(distance_r_mm, magnetic_moment_direction, mu_magnitude):
    """
    Calculates the magnetic field B generated by a magnetic dipole at a given point.

    Parameters:
    - distance_r_mm: Vector (in mm) from the dipole to the point where the field is measured.
    - magnetic_moment_direction: Unit vector indicating the direction of the magnetic moment.
    - mu_magnitude: Magnitude of the magnetic moment (e.g., in A·m²).

    Returns:
    - B_field_pT: Magnetic field vector at the point.
    """

    # Convert the distance vector to an array and compute its norm
    r = np.array(distance_r_mm)
    r_magnitude = np.linalg.norm(r)

    # Unit vector in the direction of r
    r_hat = r / r_magnitude
    Mu_hat = magnetic_moment_direction
    # Full magnetic moment vector (direction * magnitude)
    mu = [x * mu_magnitude for x in Mu_hat]

    # Compute the dipole field tensor: 3*r̂*r̂ᵀ - I
    tensor = 3 * np.outer(r_hat, r_hat) - np.identity(3)

    # Apply the formula: B = (μ₀ / 4π) * (tensor ⋅ μ) / |r|³
    numerator = np.matmul(tensor, mu)
    denominator = 4 * np.pi * (abs(r_magnitude)**3)

    # Magnetic field B in Tesla
    B_field = numerator / denominator

    # Convert Tesla to microTesla 
    B_field_pT = B_field *  1000000000000000

    return B_field_pT


class Controller(Sofa.Core.Controller):   
    
    def __init__(self, *args, **kwargs):
        Sofa.Core.Controller.__init__(self, *args, **kwargs)
        print(" Python::__init__::" + str(self.name.value))
        
        self.RootNode = kwargs['RootNode']
        self.RigidMO = kwargs['RigidMO']
        self.CFF = kwargs['CFF']
        self.CFFSphereROI = kwargs['CFFSphereROI']  
        self.CFFMO = kwargs['CFFMO']  
        self.articulationAngle = kwargs['articulationAngle']
        self.t = 0
        self.runArticulation = True
        self.dt = 0.01
        self.Kp = 100
        self.Ki = 10000000
        self.Kd = 1e2
        self.setpoint = 3.5
        self.previous_error = 0
        self.integral = 0
        self.closest_point = None
        self.closest_index = None

        print('Finished Init')
        displacement = 1

        grab_node = self.RootNode.ExternalRefNode
        if grab_node is None:
            return
        grab = grab_node.getObject('ExternalMO')
        if grab is None:
            return

        currentValue = list(grab.translation.value)
        currentValue[2] = displacement   

        grab.translation.value = currentValue
        grab.reinit()
        # self.t += 1 


    def pid_compute(self, variable, dt):
        error = self.setpoint - variable    
        P_out = self.Kp * error
        self.integral += error * dt
        I_out = self.Ki * self.integral
        derivative = (error - self.previous_error) / dt
        D_out = self.Kd * derivative
        output = (P_out + I_out + D_out)
        self.previous_error = error
        
        return output

        # self.ModelNode = self.RootNode.solverNode.deformableNode.model  

    def MoveCFFSphereROI(self):   

        puntos = np.array(Const.MagnetGridPoints)

        if Const.ForceTest == "NormalForce":
            trayectoria = normal_trajectory(puntos) 
            n_points = len(trayectoria)
            frames_per_point = 170 

            point_index = int((self.t // frames_per_point) % n_points)
            pos = trayectoria[point_index]

            self.CFFSphereROI.centers = [pos.tolist()]

            self.t += 1
       
    def animation(self, target, factor):
        angle_start = np.deg2rad(Const.ArticulationAngleDeg)
        angle_end   = np.deg2rad(-Const.ArticulationAngleDeg)
        angle = angle_start + (angle_end - angle_start) * 0.5 * (1 - np.sin(2 * np.pi * factor))
        target.dofs.rest_position[0][0] = angle   
        
    def updateArticulation(self):
        self.t += self.dt
        if Const.runAnimateArticulation == True:
            self.animation(self.articulationAngle, self.t % 2.0)

    def selectCenterPoint(self, positionSphere, roi_indices, positions):
        roi_positions = positions[roi_indices]
        distances = np.linalg.norm(roi_positions - positionSphere, axis=1)
        min_index = np.argmin(distances)
        closest_point = roi_positions[min_index]
        closest_index = int(roi_indices[min_index])  

        return closest_point, closest_index


    def onAnimateBeginEvent(self, eventType):

        self.updateArticulation()
        roi_indices = self.CFFSphereROI.indices.value
        positions = self.CFFMO.position
        roi_positions = positions[roi_indices]


        CurrentPositionSphere = np.array(self.CFFSphereROI.centers.value[0])
        self.closest_point, self.closest_index = self.selectCenterPoint(
                                                                            positionSphere=CurrentPositionSphere, 
                                                                            roi_indices=roi_indices, 
                                                                            positions=positions
                                                                        )
        # if self.closest_point is None:



        # variable = np.mean(roi_positions[:, 2])
        print('closet', self.closest_point)
        print('currentPositionSphere:',  CurrentPositionSphere )
        variable = self.closest_point[2]
        print('variablepositionz:', variable)
    

        error =  self.setpoint- variable

        tol = 0.005  
        if abs(error) < tol:
            if self.setpoint == 3.5:
                self.setpoint = 4   
            else:
                self.setpoint = 3.5   
        
        
        # Calculate the force with PID
        force_z = self.pid_compute(variable, self.dt)
        force_clamped = np.clip(force_z, -8.05e5, 1e10)

        self.CFF.indices = roi_indices.tolist()
        self.CFF.totalForce.value = [0, 0, force_clamped]


        print('error:', self.setpoint- variable)
        print('force:', self.CFF.totalForce.value)
        

        # Move Sphere ROI and apply force 

        if Const.indenterMotion  == True:
            self.MoveCFFSphereROI()
            # self.runArticulation = False
            # self.CFF.totalForce.value = Const.identadorForce
        self.t += 1
        # ---- Save current pose of the Sensor and Magnets ----
        np.savetxt("MagnetPose_Direct.txt", self.RigidMO.position.value[1:Const.NMagnets+1, :]) 
        np.savetxt("SensorPose_Direct.txt", self.RigidMO.position.value[Const.NMagnets+1:, :]) 

        # print(f"MagnetPose: {self.RigidMO.position.value}")       
        
        
       # ----Load saved positions----
        try:
            magnet_pose = np.loadtxt("MagnetPose_Direct.txt")
            sensor_pose = np.loadtxt("SensorPose_Direct.txt")
        except:
            print("Error reading pose files")
            return
    
        print('------------------------------------------------')


        # ---- Extract pose of magnets and sensors ----
        MagnetPose = self.RigidMO.position.value[1:Const.NMagnets+1, :]
        # print('MagnetPose:', MagnetPose)

        SensorPose = self.RigidMO.position.value[Const.NMagnets+1:, :]
        # print('SensorPose:', SensorPose)

         # ---- Extract 3D positions of magnets and sensors ----
        MagnetPosition = MagnetPose[:, :3]
        # print('Lista imanes:', MagnetPosition)
    
        SensorPosition = SensorPose[:,:3]
        # print('SensorPosition:', SensorPosition)
        GlobalMagneticField = []

        for j in range(Const.NSensors):
            
            LocalMagneticField = []
            # print(f'Distancia sensor {j} - imanes:', Dist_Sensor)
            quat_sensor = SensorPose[j, 3:7]
            MiR_Sensor = R.from_quat(quat_sensor)

            R_sensor_inv = R.from_quat(quat_sensor).inv()
            rotation_matrix_sensor_inv = R_sensor_inv.as_matrix()
            # rotation_Matrix_Sensor = MiR_Sensor.as_matrix()
            # print(f"i : {j}, quat_iman{quat_sensor} ")
            # print(f' sensor : {j}')
            # print('--------------------------------------')
            for i in range(Const.NMagnets):
                Dist_Sensor_global = SensorPosition[j] - MagnetPosition[i]
        #         # pos_iman = Lista_imanes[i]
                # print(f'Distancia: {Dist_Sensor_global}')
                delta_local = rotation_matrix_sensor_inv @ Dist_Sensor_global
                
        #         # print(f'Distancia sensor {j} a {i} - imanes:', delta_local)
                quat_Magnet = MagnetPose[i, 3:7]
                
                # print(f"i : {i}, quat_iman{quat_Magnet} ")
                MiR_Magnet = R.from_quat(quat_Magnet)  # (x, y, z, w)
                
                rotation_Matrix_Magnet = MiR_Magnet.as_matrix() 
                
                rotation_Matrix = MiR_Sensor.inv().as_matrix() @ rotation_Matrix_Magnet

                Direccion_momento_magnetico = rotation_Matrix[:, 2]
                
                # print(f"Direccion momento magnetico iman {i+1} ", Direccion_momento_magnetico)

                LocalMagneticField.append(calculate_B_field(delta_local, Direccion_momento_magnetico, Const.mu_magnitude))
            # print("LocalMagneticField: ", LocalMagneticField) 
            TotalMagneticField = np.sum(LocalMagneticField, axis=0)
            GlobalMagneticField.append(TotalMagneticField)
            # print(f"GlobalMagneticField {j}", TotalMagneticField )
        np.savetxt("campo_global.txt", GlobalMagneticField)
        

        
def createScene(rootNode):
    
    SofaRuntime.importPlugin("ArticulatedSystemPlugin")

    pluginsList = [
        'ArticulatedSystemPlugin',
        'SoftRobots',
        'SoftRobots.Inverse',
        'Sofa.Component.AnimationLoop',
        'Sofa.Component.Constraint.Lagrangian.Correction',
        'Sofa.Component.Constraint.Lagrangian.Solver',
        'Sofa.Component.Constraint.Projective',
        'Sofa.Component.IO.Mesh',
        'Sofa.Component.LinearSolver.Direct',
        'Sofa.Component.Mapping.NonLinear',
        'Sofa.Component.Mass',
        'Sofa.Component.SolidMechanics.Spring',
        'Sofa.Component.StateContainer',
        'Sofa.Component.Topology.Container.Constant',
        'Sofa.Component.Visual',
        'Sofa.GL.Component.Rendering3D',
        'Sofa.GUI.Component'
    ]

    
    scene = Scene(rootNode, plugins=pluginsList, iterative=False)
    scene.addMainHeader()
    scene.addObject('DefaultVisualManagerLoop')
    scene.addObject('FreeMotionAnimationLoop')
    scene.addObject('GenericConstraintSolver', maxIterations=1e3, tolerance=1e-5)
    scene.Simulation.addObject('GenericConstraintCorrection')
    scene.addObject('BackgroundSetting', color='0.8 0.8 0.8')
    scene.dt = 0.02
    scene.gravity = [0,  0, -9810]
    # scene.addObject('VisualStyle', displayFlags='hideWireframe showBehaviorModels hideCollisionModels hideBoundingCollisionModels showForceFields showInteractionForceFields')


    # ---- Paths to mesh files ----   
    VolumetricMeshPath = GeneratedMeshesPath + 'MagneticSkin.vtk'
    
    SurfaceMeshPath = GeneratedMeshesPath + 'MagneticSkin.stl'

    # SurfaceMeshPathForce = GeneratedMeshesPath + 'MagneticSkin_withoutMagnets.stl'
        
    #----------------------
    # Goal Node
    #---------------------- 
 
    #----------------------
    # Rigidification - start
    #----------------------          
              
     
    completeMesh = scene.addChild('completeMesh')
    completeMesh.addObject('MeshVTKLoader', name='loader', filename=VolumetricMeshPath)
    completeMesh.addObject('TetrahedronSetTopologyContainer', src='@loader', name='container')
    completeMesh.init()

    Boxes = []
    for i in range(len(Const.rigidObjectsBoxCoords)):
        boxTip = completeMesh.addObject('BoxROI', name='Tip'+str(i), box=[Const.rigidObjectsBoxCoords[i]], drawBoxes=True, 
                                        tetrahedra="@container.tetrahedra" , position="@container.position")
        Boxes.append(boxTip)
        boxTip.init()
      
    MeshTetra = completeMesh.addObject('MeshTopology', name="AllMesh", src='@loader')
    positionAllPoints = MeshTetra.findData('position').value;
    nbPoints = len(positionAllPoints)
        
    IndicesWithRigidIdx = np.empty((0,2), dtype=int)
    
    for (i,Box) in enumerate(Boxes):
        IndicesNP = np.array(Box.indices.value, dtype=int)
        NPoints = len(IndicesNP)
        RigidIdx = np.ones(NPoints,dtype=int)*i
        CurrentIndicesWithRigidIdx = np.append(IndicesNP.reshape((NPoints,1)), RigidIdx.reshape((NPoints,1)),1)
        IndicesWithRigidIdx = np.append(IndicesWithRigidIdx, CurrentIndicesWithRigidIdx,0)
    

    IndicesWithRigidIdxSorted = np.sort(IndicesWithRigidIdx[:,0],0)
    SortedIdxs = np.argsort(IndicesWithRigidIdx[:,0],0)
    SortedRigidIdxs = IndicesWithRigidIdx[:,1][SortedIdxs]

    indicesTip = IndicesWithRigidIdxSorted.tolist()   
    rigidBlocks = [IndicesWithRigidIdxSorted.tolist()] 
    
    
    DeformableIndicesTotal = []    
    
    for i in range(nbPoints):
        if i not in indicesTip:
            DeformableIndicesTotal.append(i)                                 

    freeBlocks = np.sort(DeformableIndicesTotal)    
    IdxsOrderedFreeBlocks = np.argsort(DeformableIndicesTotal)    
    indexPairs = np.array(rigidification.fillIndexPairs(nbPoints,freeBlocks,rigidBlocks))
    NPPointsDeformable = positionAllPoints[DeformableIndicesTotal,:]   
    NPSortedPointsDeformable = NPPointsDeformable[IdxsOrderedFreeBlocks, :]
    PointsDeformable = NPSortedPointsDeformable.flatten().tolist()
    pointsBody = PointsDeformable
    #deformablePoints = pointsBody
       
    pointsTip = np.array(positionAllPoints[indicesTip,:]).flatten().tolist()                                                 
    rigidIndexPerPoint = SortedRigidIdxs.tolist()



    # ----------------------------------------
    #            Articulation                           
    # ----------------------------------------
  
    
    # ---- Fixed servoBody ----
    servoBody = scene.Simulation.addChild('ServoBody')
    servoBody.addObject('MechanicalObject', name='dofs', template='Rigid3',
                        position=[[-0., 0., Const.MagneticSkinHeight/2, 0., 0., 0., 1.]],
                        showObject = False, showObjectScale=4)
    servoBody.addObject('FixedProjectiveConstraint', indices=0)
    servoBody.addObject('UniformMass', totalMass=0.01)



    # ---- Articulation angle: 1 DOF rotation  ----
    articulationAngle = scene.Simulation.addChild('Articulation')
    articulationAngle.addObject('MechanicalObject', name='dofs', template='Vec1', position=[[0]],
                                rest_position=[[Const.ArticulationAngleRad]])
    articulationAngle.addObject('RestShapeSpringsForceField', points=0, stiffness=1e12)
    articulationAngle.addObject('UniformMass', totalMass=0.01)
    articulationAngle.addObject('ArticulatedHierarchyContainer')
#     articulationAngle.addObject("EulerImplicitSolver", rayleighStiffness=0.1, rayleighMass=0.1)
#     articulationAngle.addObject("CGLinearSolver", iterations=200, tolerance=1e-12, threshold=1e-12)

    # ---- ServoWheel ----
    servoWheel = articulationAngle.addChild('ServoWheel')
    servoWheel.addObject('MechanicalObject', name='dofs', template='Rigid3',
                         position=[[0., 0., Const.MagneticSkinHeight/2., 0., 0., 0., 1.], 
                                   [0., 0., Const.MagneticSkinHeight/2., 0., 0., 0., 1.]],
                         showObject = False, showObjectScale=4)
    

    # ---- Mapping articulation control to servo and body -----
    servoWheel.addObject('ArticulatedSystemMapping', input1='@../dofs', input2='@../../ServoBody/dofs', output='@./')

   
    RigidNode = servoWheel.addChild('RigidNode')
     

    nominal_pose = [] 
    TipOrientation = [0, 0, 0, 1]       
    
    
    for center in Const.rigidObjects:
        CurrentPose = center + TipOrientation
        nominal_pose += CurrentPose
    RigidMO = RigidNode.addObject("MechanicalObject",template="Rigid3d",name="RigidMesh", position=nominal_pose, 
                                  showObject=True, showObjectScale=Const.MagneticSkinHeight/4, showIndices=False, showIndicesScale=0.03) # orientation is 240 deg away from scene origin

    # RigidNode.addObject("RigidMapping", input="@../dofs", output="@RigidMesh", index = 0)

  
    nominalPoseFreeCenters = [] 
    
    for center in Const.rigidObjects[1:Const.NMagnets+1]:
        CurrentPose = center + TipOrientation
        nominalPoseFreeCenters += CurrentPose
    
    freeCenter = scene.Simulation.addChild("freeCenter")
    freeCenter.addObject("MechanicalObject", name="dofs", template="Rigid3",
                          position=nominalPoseFreeCenters,
                          showObject=True, showObjectScale=1.5)
    freeCenter.addObject("UniformMass", totalMass=0.01)
    freeCenter.addObject("EulerImplicitSolver")
    freeCenter.addObject("SparseLDLSolver")
    freeCenter.addChild(RigidNode)
    


    #Add the sensors 
    nominalPoseSensors = [] 
    TipOrientation = [0, 0, 0, 1]
    for center in Const.SensorCenters:
        CurrentPose = center + TipOrientation
        nominalPoseSensors  += CurrentPose
        
    sensorCenter = servoWheel.addChild("sensorCenter")
    SensorMO = sensorCenter.addObject("MechanicalObject", name="dofs", template="Rigid3",
                         position=nominalPoseSensors,
                         showObject=False, showObjectScale=1.5, showIndices=True, showIndicesScale=0.02)
    sensorCenter.addObject("UniformMass", totalMass=0.01)
    sensorCenter.addObject("EulerImplicitSolver")
    sensorCenter.addObject("SparseLDLSolver")
    sensorCenter.addObject("RigidMapping", input="@Simulation/Articulation/ServoWheel/dofs", rigidIndexPerPoint=Const.indexPerPointSensor,  globalToLocalCoords=True)


    RigidifiedNode =  RigidNode.addChild('RigidifiedNode')   
    RigidifiedNode.addObject('MechanicalObject', name='RigidifiedMesh', position=pointsTip,
                             template='Vec3d', showObject=True, showObjectScale=4, showColor=1)       
    RigidifiedNode.addObject("RigidMapping", globalToLocalCoords="true", rigidIndexPerPoint=rigidIndexPerPoint)
    
    
    
    # ---- SubsetMultiMapping to connect ServoWheel, sensorCenter and freeCenter to rigid tips ----
    RigidNode.addObject('SubsetMultiMapping',
                          name="mapping",
                          input=['@Simulation/Articulation/ServoWheel/dofs',
                                 '@Simulation/freeCenter/dofs', 
                                 '@Simulation/Articulation/ServoWheel/sensorCenter/dofs'],
                          output='@./', indexPairs= [Const.IndexPairs])
    

    # --- Define Articulation center ----
    articulationCenter = articulationAngle.addChild('ArticulationCenter')
    articulationCenter.addObject('ArticulationCenter', parentIndex=0, childIndex=1, posOnParent=[0., 0., 0.], posOnChild=[0., 0., 0.])
    articulation = articulationCenter.addChild('Articulations')
    articulation.addObject('Articulation', translation=False, rotation=True, rotationAxis=[0, 0, 1], articulationIndex=0)


    
    # ---- Deformable Node -----
    deformableNode = RigidifiedNode.addChild("deformableNode")
    deformableNode.addObject('PointSetTopologyContainer', position=pointsBody)
    deformableNode.addObject('MechanicalObject', name='DeformableMech', showObject = False, showObjectScale = 4)
   
   
    model = deformableNode.addChild('model')
    RigidifiedNode.addChild(model)
    
    
    
    	#---- Heart ----
    model.addObject('EulerImplicitSolver', name='nodesolver')          
    model.addObject('ShewchukPCGLinearSolver', iterations='15', name='linearsolver', tolerance='1e-5', update_step='1')
    model.addObject('MeshVTKLoader', name='loader', filename=VolumetricMeshPath)
    model.addObject('TetrahedronSetTopologyContainer', src='@loader', name='container')
    model.addObject('MechanicalObject', name='tetras', template='Vec3', showIndices=False, showIndicesScale='4e-5', rx='0', dz='0')
    model.addObject('UniformMass', totalMass='0.09')
    model.addObject('TetrahedronFEMForceField', template='Vec3', name='FEM', method='large', poissonRatio=Const.PoissonRatio,  youngModulus=Const.YoungsModulus)               
    model.addObject('BoxROI', name='BaseROI', box=Const.BoxROIFixCoords, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")            
    model.addObject('RestShapeSpringsForceField', points='@BaseROI.indices', stiffness='1e12')                
    model.addObject("SubsetMultiMapping",name="subsetMapping",template="Vec3d,Vec3d", input='@'+deformableNode.getPathName()+'/DeformableMech' + ' ' + '@'+RigidifiedNode.getPathName()+'/RigidifiedMesh' , output='@./tetras', indexPairs=indexPairs.tolist())
    # model.addObject('BoxROI', name='EndROI', box=SmallBox, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")   
    #Test 
    model.addObject('SphereROI', template="Vec3d", name='EndROI', centers=[-10, 0, Const.MagneticSkinHeight], radii=[Const.indenterRadius], drawSphere=True)

    model.addObject('RestShapeSpringsForceField', points='@EndROI.indices', stiffness='1e12', external_rest_shape="@ExternalRefNode/ExternalMO")              



    model.addObject('MeshSTLLoader', 
                       name="ROIloader", 
                       filename='Geometries/Disk.stl', 
                       scale3d="1 1 1", 
                       translation ='1, 1, 5',
                       rotation="0 0 0")
    
    
    # ----------------------------------------
    # Visualization                          
    # ----------------------------------------
    
    
    modelVisu = model.addChild('visu')
    modelVisu.addObject('MeshSTLLoader', filename=SurfaceMeshPath, name="loader")
    modelVisu.addObject('OglModel', src="@loader", scale3d=[1, 1, 1])
    modelVisu.addObject('BarycentricMapping')


    
    #---- Sphere ROI ---- 
    CFFNode = model.addChild('CFFNode')
    CFFNode.addObject('MeshSTLLoader', filename=SurfaceMeshPath, name="loader")
    CFFMO = CFFNode.addObject('MechanicalObject', position='@loader.position') 
    CFFSphereROI = CFFNode.addObject('SphereROI', template="Vec3d", name='CFFSphereROI', centers=Const.indenterPosition, radii=[Const.indenterRadius], drawSphere=True)
    CFFSphereROI.init()              
    CFF = CFFNode.addObject('ConstantForceField', name='CFF', template='Vec3', indices='@CFFSphereROI.indices', totalForce=[0, 0, 0], showArrowSize=0.0001)                               
    CFFNode.addObject("BarycentricMapping")
    


    ExternalRefNode = rootNode.addChild("ExternalRefNode")
    ExternalRefNode.addObject('MechanicalObject', name='ExternalMO', template='Vec3', showObject=False, showObjectScale=15, showColor = [0,0,.7],
                   showIndices=False, showIndicesScale=4e-5,
                   position='@Simulation/Articulation/ServoWheel/RigidNode/RigidifiedNode/deformableNode/model/EndROI.pointsInROI')


    controller = rootNode.addObject(Controller(name="ActuationController", 
                                  RootNode=rootNode, 
                                  RigidMO=RigidMO,
                                  CFF=CFF,
                                  CFFMO=CFFMO,
                                  CFFSphereROI=CFFSphereROI,
                                  articulationAngle=articulationAngle)) 
    
        
    return scene