#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 19 09:29:11 2025

@author: benjamin
"""

# ---- Import Libraries ----
import os
import numpy as np
import Sofa
# import SofaRuntime
# from stlib3.scene import Scene
# from splib3.animation import animate
# from scipy.spatial.transform import Rotation as R
import Geometries.Constants as Const
import rigidification  
import Sofa.Core
import Sofa.constants.Key as Key
from scipy.spatial.transform import Rotation as R 


# ---- Directory Paths ----
dirPath = os.path.dirname(os.path.abspath(__file__)) + '/'
path = os.path.dirname(os.path.abspath(__file__))+'/Meshes/'
MeshesPath = os.path.dirname(os.path.abspath(__file__))+'/Geometries/'
GeneratedMeshesPath = os.path.dirname(os.path.abspath(__file__))+'/Geometries/'

TempPath = os.path.dirname(os.path.abspath(__file__))+'/Temp/'


EdgeMargin = 2  

# --- right BoxROI para el borde derecho ---
BoxROIFixCoords = [
    Const.MagneticSkinLength / 2 + Const.BoxTolerance, 
    Const.MagneticSkinWidth  / 2 + Const.BoxTolerance, 
    Const.MagneticSkinHeight  + Const.BoxTolerance,  
    Const.MagneticSkinLength / 2 - EdgeMargin,       
    -(Const.MagneticSkinWidth / 2 + Const.BoxTolerance),
     - Const.BoxTolerance  
]

# --- left BoxROI ---
BoxROIFixCoords1 = [
    -(Const.MagneticSkinLength / 2 - EdgeMargin),           
    Const.MagneticSkinWidth  / 2 + Const.BoxTolerance,   
    Const.MagneticSkinHeight + Const.BoxTolerance,       
    -(Const.MagneticSkinLength / 2 + Const.BoxTolerance),
    -(Const.MagneticSkinWidth / 2 + Const.BoxTolerance), 
    -Const.BoxTolerance                                  
]




def calculate_B_field(distance_r_mm, magnetic_moment_direction, mu_magnitude):
    """
    Calculates the magnetic field B generated by a magnetic dipole at a given point.

    Parameters:
    - distance_r_mm: Vector (in mm) from the dipole to the point where the field is measured.
    - magnetic_moment_direction: Unit vector indicating the direction of the magnetic moment.
    - mu_magnitude: Magnitude of the magnetic moment (e.g., in A·m²).

    Returns:
    - B_field_pT: Magnetic field vector at the point, in picoTesla (pT).
    """

    # Convert the distance vector to an array and compute its norm
    r = np.array(distance_r_mm)
    r_magnitude = np.linalg.norm(r)

    # Unit vector in the direction of r
    r_hat = r / r_magnitude
    Mu_hat = magnetic_moment_direction
    # Full magnetic moment vector (direction * magnitude)
    mu = [x * mu_magnitude for x in Mu_hat]

    # Compute the dipole field tensor: 3*r̂*r̂ᵀ - I
    tensor = 3 * np.outer(r_hat, r_hat) - np.identity(3)

    # Apply the formula: B = (μ₀ / 4π) * (tensor ⋅ μ) / |r|³
    numerator = np.matmul(tensor, mu)
    denominator = 4 * np.pi * (abs(r_magnitude)**3)

    # Magnetic field B in Tesla
    B_field = numerator / denominator

    # Convert Tesla to microTesla 
    B_field_pT = B_field *  1000000000000000

    return B_field_pT



class ControlKeyboard(Sofa.Core.Controller):
    def __init__(self, *a, **kw):
        Sofa.Core.Controller.__init__(self, *a, **kw)
        self.node = kw["node"]
        self.increment = 30
        # self.previousValue = [0, 0, 0]  # solo una “pierna”

    def onKeypressedEvent(self, e):
        grab_node = self.node.ExternalRefNode
        if grab_node is None:
            return  
        grab = grab_node.getObject('ExternalMO')
        if grab is None:
            # print("was not able to get MO")
            return

        # currentValue = np.array(grab.rest_position.value)
        currentValue = grab.translation
        print(f"currentValue: {currentValue}")

        # Movimientos según la tecla
        if e['key'] == Key.leftarrow:
            currentValue[0] = -self.increment
            # currentValue[:,0] = currentValue[:,0]-self.increment
        elif e['key'] == Key.rightarrow:
            currentValue[0] = self.increment
            # currentValue[:,0] = currentValue[:,0]+self.increment
        
            
        grab.translation.value = currentValue
        # grab.rest_position.value = currentValue
        grab.reinit()



class SinusoidalController(Sofa.Core.Controller):
    def __init__(self, *args, **kwargs):
        Sofa.Core.Controller.__init__(self, *args, **kwargs)
        print(" Python::__init__::" + str(self.name.value))
        self.node = kwargs['node']
        self.RigidMO = kwargs['RigidMO']
 
        self.t = 0

    def onAnimateBeginEvent(self, event):

        displacement = -0.1* np.sin(self.t *0.3)
        print(displacement )
        grab_node = self.node.ExternalRefNode
        if grab_node is None:
            return
        grab = grab_node.getObject('ExternalMO')
        if grab is None:
            return

        currentValue = list(grab.translation.value)
        currentValue[0] = displacement   

        grab.translation.value = currentValue
        grab.reinit()
        self.t += 1 

        np.savetxt("MagnetPose_Direct.txt", self.RigidMO.position.value[0:Const.NMagnets, :]) 
        np.savetxt("SensorPose_Direct.txt", self.RigidMO.position.value[Const.NMagnets:, :]) 
        
        # print(f"MagnetPose: {self.RigidMO.position.value}")       
        
        
       # ----Load saved positions----
        try:
            magnet_pose = np.loadtxt("MagnetPose_Direct.txt")
            sensor_pose = np.loadtxt("SensorPose_Direct.txt")
        except:
            print("Error reading pose files")
            return
    
        print('------------------------------------------------')


        # ---- Extract pose of magnets and sensors ----
        MagnetPose = self.RigidMO.position.value[0:Const.NMagnets, :]
        # print('MagnetPose:', MagnetPose)

        SensorPose = self.RigidMO.position.value[Const.NMagnets:, :]
        # print('SensorPose:', SensorPose)

         # ---- Extract 3D positions of magnets and sensors ----
        MagnetPosition = MagnetPose[:, :3]
        # print('Lista imanes:', MagnetPosition)
    
        SensorPosition = SensorPose[:,:3]
        # print('SensorPosition:', SensorPosition)
        GlobalMagneticField = []

        for j in range(Const.NSensors):
            
            LocalMagneticField = []
            # print(f'Distancia sensor {j} - imanes:', Dist_Sensor)
            quat_sensor = SensorPose[j, 3:7]
            MiR_Sensor = R.from_quat(quat_sensor)

            R_sensor_inv = R.from_quat(quat_sensor).inv()
            rotation_matrix_sensor_inv = R_sensor_inv.as_matrix()
            # rotation_Matrix_Sensor = MiR_Sensor.as_matrix()
            # print(f"i : {j}, quat_iman{quat_sensor} ")
            # print(f' sensor : {j}')
            # print('--------------------------------------')
            for i in range(Const.NMagnets):
                Dist_Sensor_global = SensorPosition[j] - MagnetPosition[i]
        #         # pos_iman = Lista_imanes[i]
                
                delta_local = rotation_matrix_sensor_inv @ Dist_Sensor_global
                
        #         # print(f'Distancia sensor {j} a {i} - imanes:', delta_local)
                quat_Magnet = MagnetPose[i, 3:7]
                
                # print(f"i : {i}, quat_iman{quat_Magnet} ")
                MiR_Magnet = R.from_quat(quat_Magnet)  # (x, y, z, w)
                
                rotation_Matrix_Magnet = MiR_Magnet.as_matrix() 
                
                rotation_Matrix = MiR_Sensor.inv().as_matrix() @ rotation_Matrix_Magnet

                Direccion_momento_magnetico = rotation_Matrix[:, 2]
                
                # print(f"Direccion momento magnetico iman {i+1} ", Direccion_momento_magnetico)

                LocalMagneticField.append(calculate_B_field(delta_local, Direccion_momento_magnetico, Const.mu_magnitude))
            # print("LocalMagneticField: ", LocalMagneticField) 
            TotalMagneticField = np.sum(LocalMagneticField, axis=0)
            GlobalMagneticField.append(TotalMagneticField)
            # print(f"GlobalMagneticField {j}", TotalMagneticField )
        np.savetxt("campo_global.txt", GlobalMagneticField)

# class FixedController(Sofa.Core.Controller):
#     # def __init__(self, node, displacement=Const.displacement):
#     def __init__(self, *args, **kwargs):
#         Sofa.Core.Controller.__init__(self, *args, **kwargs)
#         print(" Python::__init__::" + str(self.name.value))
#         self.node = kwargs['node']
#         self.RigidMO = kwargs['RigidMO']
#         self.displacement  = kwargs['displacement']  
#         self.initialized = False

#     def onAnimateBeginEvent(self, event):
#         if self.initialized:
#             return  

#         grab_node = self.node.ExternalRefNode
#         if grab_node is None:
#             return
#         grab = grab_node.getObject('ExternalMO')
#         if grab is None:
#             return

#         currentValue = list(grab.translation.value)

#         print('currentValue', currentValue)
#         currentValue[0] = self.displacement  
#         grab.translation.value = currentValue
#         grab.reinit()
#         # self.initialized = True

#         np.savetxt("MagnetPose_Direct.txt", self.RigidMO.position.value[0:Const.NMagnets, :]) 
#         np.savetxt("SensorPose_Direct.txt", self.RigidMO.position.value[Const.NMagnets:, :]) 
        
#         # print(f"MagnetPose: {self.RigidMO.position.value}")       
        
        
#        # ----Load saved positions----
#         try:
#             magnet_pose = np.loadtxt("MagnetPose_Direct.txt")
#             sensor_pose = np.loadtxt("SensorPose_Direct.txt")
#         except:
#             print("Error reading pose files")
#             return
    
#         print('------------------------------------------------')


#         # ---- Extract pose of magnets and sensors ----
#         MagnetPose = self.RigidMO.position.value[0:Const.NMagnets, :]
#         # print('MagnetPose:', MagnetPose)

#         SensorPose = self.RigidMO.position.value[Const.NMagnets:, :]
#         # print('SensorPose:', SensorPose)

#          # ---- Extract 3D positions of magnets and sensors ----
#         MagnetPosition = MagnetPose[:, :3]
#         # print('Lista imanes:', MagnetPosition)
    
#         SensorPosition = SensorPose[:,:3]
#         # print('SensorPosition:', SensorPosition)
#         GlobalMagneticField = []

#         for j in range(Const.NSensors):
            
#             LocalMagneticField = []
#             # print(f'Distancia sensor {j} - imanes:', Dist_Sensor)
#             quat_sensor = SensorPose[j, 3:7]
#             MiR_Sensor = R.from_quat(quat_sensor)

#             R_sensor_inv = R.from_quat(quat_sensor).inv()
#             rotation_matrix_sensor_inv = R_sensor_inv.as_matrix()
#             # rotation_Matrix_Sensor = MiR_Sensor.as_matrix()
#             # print(f"i : {j}, quat_iman{quat_sensor} ")
#             # print(f' sensor : {j}')
#             # print('--------------------------------------')
#             for i in range(Const.NMagnets):
#                 Dist_Sensor_global = SensorPosition[j] - MagnetPosition[i]
#         #         # pos_iman = Lista_imanes[i]
                
#                 delta_local = rotation_matrix_sensor_inv @ Dist_Sensor_global
                
#         #         # print(f'Distancia sensor {j} a {i} - imanes:', delta_local)
#                 quat_Magnet = MagnetPose[i, 3:7]
                
#                 # print(f"i : {i}, quat_iman{quat_Magnet} ")
#                 MiR_Magnet = R.from_quat(quat_Magnet)  # (x, y, z, w)
                
#                 rotation_Matrix_Magnet = MiR_Magnet.as_matrix() 
                
#                 rotation_Matrix = MiR_Sensor.inv().as_matrix() @ rotation_Matrix_Magnet

#                 Direccion_momento_magnetico = rotation_Matrix[:, 2]
                
#                 # print(f"Direccion momento magnetico iman {i+1} ", Direccion_momento_magnetico)

#                 LocalMagneticField.append(calculate_B_field(delta_local, Direccion_momento_magnetico, Const.mu_magnitude))
#             # print("LocalMagneticField: ", LocalMagneticField) 
#             TotalMagneticField = np.sum(LocalMagneticField, axis=0)
#             GlobalMagneticField.append(TotalMagneticField)
#             # print(f"GlobalMagneticField {j}", TotalMagneticField )
#         np.savetxt("campo_global.txt", GlobalMagneticField)



def createScene(rootNode):
                
    rootNode.addObject('RequiredPlugin', pluginName='SofaPython3 SoftRobots SoftRobots.Inverse')
    rootNode.addObject('VisualStyle', displayFlags='hideWireframe showBehaviorModels hideCollisionModels hideBoundingCollisionModels showForceFields showInteractionForceFields')
    rootNode.findData('gravity').value = [0, 0, -0] 
    rootNode.findData('dt').value = 0.02

    rootNode.addObject('FreeMotionAnimationLoop')
    rootNode.addObject('QPInverseProblemSolver', printLog='0', epsilon="1e-1", maxIterations="1000", tolerance="1e-5")
    #rootNode.addObject('QPInverseProblemSolver', printLog=False, epsilon="0.0001", maxIterations="1000", tolerance="1e-5")

    rootNode.addObject('GenericConstraintSolver', tolerance="1e-12", maxIterations="10000")

    #rootNode.addObject('BackgroundSetting', color='0 0.168627 0.211765')
    rootNode.addObject('BackgroundSetting', color='0.85 0.85 0.85')
    
    
    rootNode.addObject('LightManager')
    rootNode.addObject(
        "PositionalLight",
        name="light1",
        color="0.8 0.8 0.8",
        position=[0, 0, 50],
    )
    rootNode.addObject(
        "PositionalLight",
        name="light2",
        color="0.8 0.8 0.8",
        position=[0, 0, -50],
    )
    

    # rootNode.addObject()
    # ---- Paths to mesh files ----   
    VolumetricMeshPath = GeneratedMeshesPath + 'MagneticSkin.vtk'
    
    SurfaceMeshPath = GeneratedMeshesPath + 'MagneticSkin.stl'
    
    
    # rootNode.addObject(SinusoidalController(node=rootNode, RigidMO = RigidMO))
    # rootNode.addObject(FixedController(rootNode))

    #----------------------
    # Goal Node
    #---------------------- 
 
    #----------------------
    # Rigidification - start
    #----------------------          
                   
    completeMesh = rootNode.addChild('completeMesh')
    completeMesh.addObject('MeshVTKLoader', name='loader', filename=VolumetricMeshPath)
    completeMesh.addObject('TetrahedronSetTopologyContainer', src='@loader', name='container')
    completeMesh.init()
    MeshTetra = completeMesh.addObject('MeshTopology', name="AllMesh", src='@loader')

    

    
    #---- Create BoxROIs ----
    Boxes = []
    for i in range(len(Const.rigidObjectsBoxCoords[1:])):
        boxTip = completeMesh.addObject('BoxROI', name='Tip'+str(i), box=[Const.rigidObjectsBoxCoords[i+1]], drawBoxes=False, tetrahedra="@container.tetrahedra" , position="@container.position")
        Boxes.append(boxTip)
        boxTip.init()
      
    positionAllPoints = MeshTetra.findData('position').value;
    nbPoints = len(positionAllPoints)
    
    
    IndicesWithRigidIdx = np.empty((0,2), dtype=int)
    
    for (i,Box) in enumerate(Boxes):
        IndicesNP = np.array(Box.indices.value, dtype=int)
        NPoints = len(IndicesNP)
        RigidIdx = np.ones(NPoints,dtype=int)*i
        CurrentIndicesWithRigidIdx = np.append(IndicesNP.reshape((NPoints,1)), RigidIdx.reshape((NPoints,1)),1)
        IndicesWithRigidIdx = np.append(IndicesWithRigidIdx, CurrentIndicesWithRigidIdx,0)
    

    IndicesWithRigidIdxSorted = np.sort(IndicesWithRigidIdx[:,0],0)
    SortedIdxs = np.argsort(IndicesWithRigidIdx[:,0],0)
    SortedRigidIdxs = IndicesWithRigidIdx[:,1][SortedIdxs]
    indicesTip = IndicesWithRigidIdxSorted.tolist()
    rigidBlocks = [IndicesWithRigidIdxSorted.tolist()] 
    
    DeformableIndicesTotal = []    
    
    for i in range(nbPoints):
        if i not in indicesTip:
            DeformableIndicesTotal.append(i)                                 

    freeBlocks = np.sort(DeformableIndicesTotal)    
    IdxsOrderedFreeBlocks = np.argsort(DeformableIndicesTotal)    
    indexPairs = np.array(rigidification.fillIndexPairs(nbPoints,freeBlocks,rigidBlocks))
    NPPointsDeformable = positionAllPoints[DeformableIndicesTotal,:]   
    NPSortedPointsDeformable = NPPointsDeformable[IdxsOrderedFreeBlocks, :]
    PointsDeformable = NPSortedPointsDeformable.flatten().tolist()
    pointsBody = PointsDeformable
    #deformablePoints = pointsBody
       
    pointsTip = np.array(positionAllPoints[indicesTip,:]).flatten().tolist()                                                 
    rigidIndexPerPoint = SortedRigidIdxs.tolist()


    
    solverNode = rootNode.addChild("solverNode")
    solverNode.addObject('EulerImplicitSolver',rayleighStiffness="0.1", rayleighMass="0.1")
    solverNode.addObject('SparseLDLSolver',name='preconditioner')
    solverNode.addObject('GenericConstraintCorrection', linearSolver='@preconditioner')


    RigidNode= solverNode.addChild('RigidNode')
     
    
    nominal_pose = [] 
    TipOrientation = [0, 0, 0, 1]       
    
    
    for center in Const.rigidObjects[1:]:
        CurrentPose = center + TipOrientation
        nominal_pose += CurrentPose
    RigidMO = RigidNode.addObject("MechanicalObject",template="Rigid3d",name="RigidMesh", position=nominal_pose, 
                                  showObject=True, showObjectScale=2, showIndices=True) # orientation is 240 deg away from scene origin


    RigidifiedNode =  RigidNode.addChild('RigidifiedNode')   
    RigidifiedNode.addObject('MechanicalObject', name='RigidifiedMesh', position=pointsTip,
                             template='Vec3d', showObject=True, showObjectScale=5, showColor=1)       
    RigidifiedNode.addObject("RigidMapping", globalToLocalCoords="true", rigidIndexPerPoint=rigidIndexPerPoint)
    

    # ---- Deformable Node -----
    deformableNode = RigidifiedNode.addChild("deformableNode")
    deformableNode.addObject('PointSetTopologyContainer', position=pointsBody)
    deformableNode.addObject('MechanicalObject', name='DeformableMech', showObject = False, showObjectScale = 4)
    # deformableNode.addObject('BarycentricMapping', input='@model/tetras', output='@DeformableMech')
    

    model = deformableNode.addChild('model')
    RigidifiedNode.addChild(model)
    

    	#---- Heart ----
    model.addObject('EulerImplicitSolver', name='nodesolver')          
    model.addObject('ShewchukPCGLinearSolver', iterations='15', name='linearsolver', tolerance='1e-5', update_step='1')
    model.addObject('MeshVTKLoader', name='loader', filename=VolumetricMeshPath)
    model.addObject('TetrahedronSetTopologyContainer', src='@loader', name='container')
    model.addObject('MechanicalObject', name='tetras', template='Vec3', showIndices=False, showIndicesScale='4e-5', rx='0', dz='0')
    model.addObject('UniformMass', totalMass='0.09')
    model.addObject('TetrahedronFEMForceField', template='Vec3', name='FEM', method='large', poissonRatio=Const.PoissonRatio,  youngModulus=Const.YoungsModulus)               
    model.addObject('BoxROI', name='BaseROI', box=BoxROIFixCoords, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")              
    model.addObject('RestShapeSpringsForceField', points='@BaseROI.indices', stiffness='1e12')              
    model.addObject("SubsetMultiMapping",name="subsetMapping",template="Vec3d,Vec3d", input='@'+deformableNode.getPathName()+'/DeformableMech' + ' ' + '@'+RigidifiedNode.getPathName()+'/RigidifiedMesh' , output='@./tetras', indexPairs=indexPairs.tolist())
    model.addObject('BoxROI', name='EndROI', box=BoxROIFixCoords1, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")              
    model.addObject('RestShapeSpringsForceField', points='@EndROI.indices', stiffness='1e12', external_rest_shape="@ExternalRefNode/ExternalMO")              

    
    # ----------------------------------------
    # Visualization                          
    # ----------------------------------------
    
    modelVisu = model.addChild('visu')
    modelVisu.addObject('MeshSTLLoader', filename=SurfaceMeshPath, name="loader")
    modelVisu.addObject('OglModel', src="@loader", scale3d=[1, 1, 1])
    modelVisu.addObject('BarycentricMapping')
    
    ExternalRefNode = rootNode.addChild("ExternalRefNode")
    ExternalRefNode.addObject('MechanicalObject', name='ExternalMO', template='Vec3', showObject=False, showObjectScale=15, showColor = [0,0,.7],
                   showIndices=False, showIndicesScale=4e-5,
                   position='@../solverNode/RigidNode/RigidifiedNode/deformableNode/model/EndROI.pointsInROI')


    rootNode.addObject(SinusoidalController(node=rootNode, RigidMO = RigidMO))
    # rootNode.addObject(FixedController(
    #                                     node=rootNode,
    #                                     RigidMO=RigidMO,  
    #                                     displacement=Const.displacement
    #                                 ))

    return rootNode